apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl-pods
#  namespace: mesh-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      nodeSelector:
        zone: app  # Replace with your actual node label
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - curl
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: curl
          image: curlimages/curl:latest
          command: ["sh", "-c"]
          args:
            - |
              echo "Curling to detect IP..." && echo "IP: ," $(curl -Ss http://ifconfig.me/ip) && sleep 3600
